name: Hi User!

on:
  push:
    branches:
      - main

jobs: 
  hi_user_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hi User!"
      - name: Now it is
        run: |
          date -R
      - name: Directory content
        run: |
          ls -l