name: Periodic Health Check

on:
  push:
    branches:
      - main

jobs:
    simple_healthcheck:
        runs-on: ubuntu-20.04
        steps:
            - name: Check Pokedex
              uses: jtalk/url-health-check-action@v4
              with:
                # Check the following URLs one by one sequentially
                url: https://full-stack-open-pokedex-7uao.onrender.com|https://full-stack-open-pokedex-7uao.onrender.com/health
            

